const products = [
  {
    _id: "1",
    name: "Boys jacket",
    image: "/images/jacket.jpg",
    description: "Warm jacket for boys aged 3-5 years old",
    brand: "H&M",
    category: "Clothing",
    price: 350,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Unisex Romper",
    image: "/images/romper.jpg",
    description: "Romper for both boys and girls aged 2-6",
    brand: "LC Waikiki",
    category: "Clothing",
    price: 200,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Adidas Superstar - Girls",
    image: "/images/shoes.jpg",
    description: "Adidas Superstar for girls aged 6",
    brand: "Adidas",
    category: "Shoes",
    price: 500,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Short trousers for boys",
    image: "/images/trousers_sh.jpg",
    description: "Short trousers for boys aged 4 suitable for swimming",
    brand: "North Face",
    category: "Clothing",
    price: 350,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Boys long sleeved t-shirts",
    image: "/images/tshirt_ls.jpg",
    description:
      "Long sleeved t-shirts for boys aged 3. Suitable for cold weather",
    brand: "Balenciaga",
    category: "Clothing",
    price: 250,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "Short sleeved t-shirts",
    image: "/images/tshirt_ss.jpg",
    description:
      "Stylish short sleeved t-shirts for boys aged 3 suitable for hot seasons,",
    brand: "Puma",
    category: "Clothing",
    price: 200,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
